name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: BuildEnv

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push udpserver Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: qinbatista/udpserver:latest
          build-args: |
            AWS_KEY=${{ secrets.AWS_KEY }}
            AWS_SECRET=${{ secrets.AWS_ACCESS }}
            IPV4_DOMAIN_UPDATE_LAMBDA=${{ vars.IPV4_DOMAIN_UPDATE_LAMBDA }}
            SERVER_DOMAIN_NAME=${{ vars.SERVER_DOMAIN_NAME }}

      - name: Build and push udpclient Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./Client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: qinbatista/udpclient:latest
          build-args: |
            AWS_KEY=${{ secrets.AWS_KEY }}
            AWS_SECRET=${{ secrets.AWS_ACCESS }}
            CLIENT_DOMAIN_NAME=${{ vars.CLIENT_DOMAIN_NAME }}
            SERVER_DOMAIN_NAME=${{ vars.SERVER_DOMAIN_NAME }}